package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opensds/opensds/api/openapi-spec/models"
)

// HTTP code for type CreateVolumeOK
const CreateVolumeOKCode int = 200

/*CreateVolumeOK OK

swagger:response createVolumeOK
*/
type CreateVolumeOK struct {

	/*
	  In: Body
	*/
	Payload *models.VolumeResponse `json:"body,omitempty"`
}

// NewCreateVolumeOK creates CreateVolumeOK with default headers values
func NewCreateVolumeOK() *CreateVolumeOK {
	return &CreateVolumeOK{}
}

// WithPayload adds the payload to the create volume o k response
func (o *CreateVolumeOK) WithPayload(payload *models.VolumeResponse) *CreateVolumeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create volume o k response
func (o *CreateVolumeOK) SetPayload(payload *models.VolumeResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateVolumeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
