package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opensds/opensds/api/openapi-spec/models"
)

// HTTP code for type GetVersionv1OK
const GetVersionv1OKCode int = 200

/*GetVersionv1OK OK

swagger:response getVersionv1OK
*/
type GetVersionv1OK struct {

	/*
	  In: Body
	*/
	Payload *models.VersionInfo `json:"body,omitempty"`
}

// NewGetVersionv1OK creates GetVersionv1OK with default headers values
func NewGetVersionv1OK() *GetVersionv1OK {
	return &GetVersionv1OK{}
}

// WithPayload adds the payload to the get versionv1 o k response
func (o *GetVersionv1OK) WithPayload(payload *models.VersionInfo) *GetVersionv1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get versionv1 o k response
func (o *GetVersionv1OK) SetPayload(payload *models.VersionInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVersionv1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
