package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opensds/opensds/api/openapi-spec/models"
)

// HTTP code for type ListSharesOK
const ListSharesOKCode int = 200

/*ListSharesOK OK

swagger:response listSharesOK
*/
type ListSharesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ShareResponse `json:"body,omitempty"`
}

// NewListSharesOK creates ListSharesOK with default headers values
func NewListSharesOK() *ListSharesOK {
	return &ListSharesOK{}
}

// WithPayload adds the payload to the list shares o k response
func (o *ListSharesOK) WithPayload(payload []*models.ShareResponse) *ListSharesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list shares o k response
func (o *ListSharesOK) SetPayload(payload []*models.ShareResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSharesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.ShareResponse, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
