package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// OperateVolumeHandlerFunc turns a function with the right signature into a operate volume handler
type OperateVolumeHandlerFunc func(OperateVolumeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OperateVolumeHandlerFunc) Handle(params OperateVolumeParams) middleware.Responder {
	return fn(params)
}

// OperateVolumeHandler interface for that can handle valid operate volume params
type OperateVolumeHandler interface {
	Handle(OperateVolumeParams) middleware.Responder
}

// NewOperateVolume creates a new http.Handler for the operate volume operation
func NewOperateVolume(ctx *middleware.Context, handler OperateVolumeHandler) *OperateVolume {
	return &OperateVolume{Context: ctx, Handler: handler}
}

/*OperateVolume swagger:route POST /api/v1/volumes/action/{resourceType}/{id} operateVolume

opreate specified volume in specified backend resource

*/
type OperateVolume struct {
	Context *middleware.Context
	Handler OperateVolumeHandler
}

func (o *OperateVolume) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewOperateVolumeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
