package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opensds/opensds/api/openapi-spec/models"
)

// HTTP code for type UpdateShareOK
const UpdateShareOKCode int = 200

/*UpdateShareOK OK

swagger:response updateShareOK
*/
type UpdateShareOK struct {

	/*
	  In: Body
	*/
	Payload *models.ShareResponse `json:"body,omitempty"`
}

// NewUpdateShareOK creates UpdateShareOK with default headers values
func NewUpdateShareOK() *UpdateShareOK {
	return &UpdateShareOK{}
}

// WithPayload adds the payload to the update share o k response
func (o *UpdateShareOK) WithPayload(payload *models.ShareResponse) *UpdateShareOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update share o k response
func (o *UpdateShareOK) SetPayload(payload *models.ShareResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateShareOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
