package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opensds/opensds/api/openapi-spec/models"
)

// HTTP code for type UpdateVolumeOK
const UpdateVolumeOKCode int = 200

/*UpdateVolumeOK OK

swagger:response updateVolumeOK
*/
type UpdateVolumeOK struct {

	/*
	  In: Body
	*/
	Payload *models.VolumeResponse `json:"body,omitempty"`
}

// NewUpdateVolumeOK creates UpdateVolumeOK with default headers values
func NewUpdateVolumeOK() *UpdateVolumeOK {
	return &UpdateVolumeOK{}
}

// WithPayload adds the payload to the update volume o k response
func (o *UpdateVolumeOK) WithPayload(payload *models.VolumeResponse) *UpdateVolumeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update volume o k response
func (o *UpdateVolumeOK) SetPayload(payload *models.VolumeResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateVolumeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
