#!/bin/bash

# Copyright 2019 The OpenSDS Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
echo "" > coverage.txt

MODEL_PACKAGE=github.com/opensds/opensds/pkg/model
PROTOBUF_PACKAGE=github.com/opensds/opensds/pkg/model/proto

for testpkg in $(go list ./osdsctl/... ./client/... ./pkg/... ./contrib/...); do
  test $testpkg == "$MODEL_PACKAGE" && continue
  test $testpkg == "$PROTOBUF_PACKAGE" && continue
  go test -race -covermode=atomic -coverprofile=profile.out "$testpkg"
  if [ -f profile.out ]; then
    cat profile.out >> coverage.txt
    rm profile.out
  fi
done
