// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dock.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	dock.proto

It has these top-level messages:
	CreateVolumeOpts
	DeleteVolumeOpts
	ExtendVolumeOpts
	CreateVolumeSnapshotOpts
	DeleteVolumeSnapshotOpts
	CreateAttachmentOpts
	DeleteAttachmentOpts
	HostInfo
	CreateVolumeGroupOpts
	UpdateVolumeGroupOpts
	DeleteVolumeGroupOpts
	AttachVolumeOpts
	DetachVolumeOpts
	GenericResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// CreateVolumeOpts is a structure which indicates all required properties
// for creating a volume.
type CreateVolumeOpts struct {
	// The uuid of the volume, optional when creating.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The name of the volume, required.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// The requested capacity of the volume, required.
	Size int64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// The description of the volume, optional.
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	// When create volume from snapshot, this field is required.
	SnapshotId string `protobuf:"bytes,5,opt,name=snapshotId" json:"snapshotId,omitempty"`
	// The locality that volume belongs to, required.
	AvailabilityZone string `protobuf:"bytes,6,opt,name=availabilityZone" json:"availabilityZone,omitempty"`
	// The service level that volume belongs to, required.
	ProfileId string `protobuf:"bytes,7,opt,name=profileId" json:"profileId,omitempty"`
	// The uuid of the pool on which volume will be created, required.
	PoolId string `protobuf:"bytes,8,opt,name=poolId" json:"poolId,omitempty"`
	// The name of the pool on which volume will be created, required.
	PoolName string `protobuf:"bytes,9,opt,name=poolName" json:"poolName,omitempty"`
	// The metadata of the volume, optional.
	Metadata map[string]string `protobuf:"bytes,10,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The storage driver type.
	DriverName string `protobuf:"bytes,11,opt,name=driverName" json:"driverName,omitempty"`
	// The Context
	Context string `protobuf:"bytes,12,opt,name=context" json:"context,omitempty"`
}

func (m *CreateVolumeOpts) Reset()                    { *m = CreateVolumeOpts{} }
func (m *CreateVolumeOpts) String() string            { return proto1.CompactTextString(m) }
func (*CreateVolumeOpts) ProtoMessage()               {}
func (*CreateVolumeOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateVolumeOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateVolumeOpts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVolumeOpts) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateVolumeOpts) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateVolumeOpts) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *CreateVolumeOpts) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

func (m *CreateVolumeOpts) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *CreateVolumeOpts) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *CreateVolumeOpts) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *CreateVolumeOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CreateVolumeOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *CreateVolumeOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// DeleteVolumeOpts is a structure which indicates all required properties
// for deleting a volume.
type DeleteVolumeOpts struct {
	// The uuid of the volume, required.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The metadata of the volume, optional.
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The storage driver type.
	DriverName string `protobuf:"bytes,3,opt,name=driverName" json:"driverName,omitempty"`
	// The Context
	Context string `protobuf:"bytes,4,opt,name=context" json:"context,omitempty"`
}

func (m *DeleteVolumeOpts) Reset()                    { *m = DeleteVolumeOpts{} }
func (m *DeleteVolumeOpts) String() string            { return proto1.CompactTextString(m) }
func (*DeleteVolumeOpts) ProtoMessage()               {}
func (*DeleteVolumeOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteVolumeOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteVolumeOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DeleteVolumeOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *DeleteVolumeOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// ExtendVolumeOpts is a structure which indicates all required properties
// for Extending a volume.
type ExtendVolumeOpts struct {
	// The uuid of the volume, optional when creating.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The name of the volume, required.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// The requested capacity of the volume, required.
	Size int64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// The description of the volume, optional.
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	// When create volume from snapshot, this field is required.
	SnapshotId string `protobuf:"bytes,5,opt,name=snapshotId" json:"snapshotId,omitempty"`
	// The locality that volume belongs to, required.
	AvailabilityZone string `protobuf:"bytes,6,opt,name=availabilityZone" json:"availabilityZone,omitempty"`
	// The service level that volume belongs to, required.
	ProfileId string `protobuf:"bytes,7,opt,name=profileId" json:"profileId,omitempty"`
	// The uuid of the pool on which volume will be created, required.
	PoolId string `protobuf:"bytes,8,opt,name=poolId" json:"poolId,omitempty"`
	// The name of the pool on which volume will be created, required.
	PoolName string `protobuf:"bytes,9,opt,name=poolName" json:"poolName,omitempty"`
	// The metadata of the volume, optional.
	Metadata map[string]string `protobuf:"bytes,10,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The storage driver type.
	DriverName string `protobuf:"bytes,11,opt,name=driverName" json:"driverName,omitempty"`
	// The Context
	Context string `protobuf:"bytes,12,opt,name=context" json:"context,omitempty"`
}

func (m *ExtendVolumeOpts) Reset()                    { *m = ExtendVolumeOpts{} }
func (m *ExtendVolumeOpts) String() string            { return proto1.CompactTextString(m) }
func (*ExtendVolumeOpts) ProtoMessage()               {}
func (*ExtendVolumeOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExtendVolumeOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExtendVolumeOpts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExtendVolumeOpts) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ExtendVolumeOpts) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ExtendVolumeOpts) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *ExtendVolumeOpts) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

func (m *ExtendVolumeOpts) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *ExtendVolumeOpts) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *ExtendVolumeOpts) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *ExtendVolumeOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ExtendVolumeOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *ExtendVolumeOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// CreateVolumeSnapshotOpts is a structure which indicates all required
// properties for creating a volume snapshot.
type CreateVolumeSnapshotOpts struct {
	// The uuid of the volume snapshot, optional.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The name of the volume snapshot, required.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// The size of the volume that snapshot belongs to, required.
	Size int64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// The description of the volume snapshot, optional.
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	// The uuid of the volume that snapshot belongs to, required.
	VolumeId string `protobuf:"bytes,5,opt,name=volumeId" json:"volumeId,omitempty"`
	// The metadata of the volume snapshot, optional.
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The storage driver type.
	DriverName string `protobuf:"bytes,7,opt,name=driverName" json:"driverName,omitempty"`
	// The Context
	Context string `protobuf:"bytes,8,opt,name=context" json:"context,omitempty"`
}

func (m *CreateVolumeSnapshotOpts) Reset()                    { *m = CreateVolumeSnapshotOpts{} }
func (m *CreateVolumeSnapshotOpts) String() string            { return proto1.CompactTextString(m) }
func (*CreateVolumeSnapshotOpts) ProtoMessage()               {}
func (*CreateVolumeSnapshotOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateVolumeSnapshotOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateVolumeSnapshotOpts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVolumeSnapshotOpts) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateVolumeSnapshotOpts) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateVolumeSnapshotOpts) GetVolumeId() string {
	if m != nil {
		return m.VolumeId
	}
	return ""
}

func (m *CreateVolumeSnapshotOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CreateVolumeSnapshotOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *CreateVolumeSnapshotOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// DeleteVolumeSnapshotOpts is a structure which indicates all required
// properties for deleting a volume snapshot.
type DeleteVolumeSnapshotOpts struct {
	// The uuid of the volume snapshot, required.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The uuid of the volume that snapshot belongs to, required.
	VolumeId string `protobuf:"bytes,2,opt,name=volumeId" json:"volumeId,omitempty"`
	// The metadata of the volume snapshot, optional.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The storage driver type.
	DriverName string `protobuf:"bytes,4,opt,name=driverName" json:"driverName,omitempty"`
	// The Context
	Context string `protobuf:"bytes,5,opt,name=context" json:"context,omitempty"`
}

func (m *DeleteVolumeSnapshotOpts) Reset()                    { *m = DeleteVolumeSnapshotOpts{} }
func (m *DeleteVolumeSnapshotOpts) String() string            { return proto1.CompactTextString(m) }
func (*DeleteVolumeSnapshotOpts) ProtoMessage()               {}
func (*DeleteVolumeSnapshotOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteVolumeSnapshotOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteVolumeSnapshotOpts) GetVolumeId() string {
	if m != nil {
		return m.VolumeId
	}
	return ""
}

func (m *DeleteVolumeSnapshotOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DeleteVolumeSnapshotOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *DeleteVolumeSnapshotOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// CreateAttachmentOpts is a structure which indicates all required
// properties for creating a volume attachment.
type CreateAttachmentOpts struct {
	// The uuid of the volume attachment, optional.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The uuid of the volume, required.
	VolumeId string `protobuf:"bytes,2,opt,name=volumeId" json:"volumeId,omitempty"`
	// This field indicates if the volume is attached locally, optional.
	DoLocalAttach bool `protobuf:"varint,3,opt,name=doLocalAttach" json:"doLocalAttach,omitempty"`
	// This field indicates if the volume is attached multiple times, optional.
	MultiPath bool `protobuf:"varint,4,opt,name=multiPath" json:"multiPath,omitempty"`
	// The infomation of the host node on which the volume will be attached.
	HostInfo *HostInfo `protobuf:"bytes,5,opt,name=hostInfo" json:"hostInfo,omitempty"`
	// The metadata of the volume attachment, optional.
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The storage driver type.
	DriverName string `protobuf:"bytes,7,opt,name=driverName" json:"driverName,omitempty"`
	// The Context
	Context string `protobuf:"bytes,8,opt,name=context" json:"context,omitempty"`
}

func (m *CreateAttachmentOpts) Reset()                    { *m = CreateAttachmentOpts{} }
func (m *CreateAttachmentOpts) String() string            { return proto1.CompactTextString(m) }
func (*CreateAttachmentOpts) ProtoMessage()               {}
func (*CreateAttachmentOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateAttachmentOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateAttachmentOpts) GetVolumeId() string {
	if m != nil {
		return m.VolumeId
	}
	return ""
}

func (m *CreateAttachmentOpts) GetDoLocalAttach() bool {
	if m != nil {
		return m.DoLocalAttach
	}
	return false
}

func (m *CreateAttachmentOpts) GetMultiPath() bool {
	if m != nil {
		return m.MultiPath
	}
	return false
}

func (m *CreateAttachmentOpts) GetHostInfo() *HostInfo {
	if m != nil {
		return m.HostInfo
	}
	return nil
}

func (m *CreateAttachmentOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CreateAttachmentOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *CreateAttachmentOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// DeleteAttachmentOpts is a structure which indicates all required
// properties for deleting a volume attachment.
type DeleteAttachmentOpts struct {
	// The uuid of the volume attachment, optional.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The uuid of the volume, required.
	VolumeId string `protobuf:"bytes,2,opt,name=volumeId" json:"volumeId,omitempty"`
	// The infomation of the host node on which the volume will be attached.
	HostInfo *HostInfo `protobuf:"bytes,3,opt,name=hostInfo" json:"hostInfo,omitempty"`
	// The metadata of the volume attachment, optional.
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The storage driver type.
	DriverName string `protobuf:"bytes,5,opt,name=driverName" json:"driverName,omitempty"`
	// The Context
	Context string `protobuf:"bytes,6,opt,name=context" json:"context,omitempty"`
}

func (m *DeleteAttachmentOpts) Reset()                    { *m = DeleteAttachmentOpts{} }
func (m *DeleteAttachmentOpts) String() string            { return proto1.CompactTextString(m) }
func (*DeleteAttachmentOpts) ProtoMessage()               {}
func (*DeleteAttachmentOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteAttachmentOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteAttachmentOpts) GetVolumeId() string {
	if m != nil {
		return m.VolumeId
	}
	return ""
}

func (m *DeleteAttachmentOpts) GetHostInfo() *HostInfo {
	if m != nil {
		return m.HostInfo
	}
	return nil
}

func (m *DeleteAttachmentOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DeleteAttachmentOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *DeleteAttachmentOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type HostInfo struct {
	// The platform of the host, such as "x86_64"
	Platform string `protobuf:"bytes,1,opt,name=platform" json:"platform,omitempty"`
	// The type of OS, such as "linux","windows", etc.
	OsType string `protobuf:"bytes,2,opt,name=osType" json:"osType,omitempty"`
	// The name of the host
	Host string `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	// The ip address of the host
	Ip string `protobuf:"bytes,4,opt,name=ip" json:"ip,omitempty"`
	// The initiator infomation, such as: "iqn.2017.com.redhat:e08039b48d5c"
	Initiator string `protobuf:"bytes,5,opt,name=initiator" json:"initiator,omitempty"`
}

func (m *HostInfo) Reset()                    { *m = HostInfo{} }
func (m *HostInfo) String() string            { return proto1.CompactTextString(m) }
func (*HostInfo) ProtoMessage()               {}
func (*HostInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *HostInfo) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *HostInfo) GetOsType() string {
	if m != nil {
		return m.OsType
	}
	return ""
}

func (m *HostInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HostInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *HostInfo) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

// CreateVolumeGroupOpts is a structure which indicates all required
// properties for creating a volume group.
type CreateVolumeGroupOpts struct {
	// The uuid of the volume group, optional when creating.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The name of the volume, required.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// The driver of the volume group.
	DriverName string `protobuf:"bytes,3,opt,name=driverName" json:"driverName,omitempty"`
	// The description of the volume, optional.
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	// When create volume from snapshot, this field is required.
	AvailabilityZone string `protobuf:"bytes,5,opt,name=availabilityZone" json:"availabilityZone,omitempty"`
	// The addVolumes contain UUIDs of volumes to be added to the group.
	AddVolumes []string `protobuf:"bytes,6,rep,name=addVolumes" json:"addVolumes,omitempty"`
	// The removeVolumes contains the volumes to be removed from the group.
	RemoveVolumes []string `protobuf:"bytes,7,rep,name=removeVolumes" json:"removeVolumes,omitempty"`
	// The pool belongs to the group.
	PoolId string `protobuf:"bytes,8,opt,name=poolId" json:"poolId,omitempty"`
	// The Context
	Context string `protobuf:"bytes,9,opt,name=context" json:"context,omitempty"`
}

func (m *CreateVolumeGroupOpts) Reset()                    { *m = CreateVolumeGroupOpts{} }
func (m *CreateVolumeGroupOpts) String() string            { return proto1.CompactTextString(m) }
func (*CreateVolumeGroupOpts) ProtoMessage()               {}
func (*CreateVolumeGroupOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateVolumeGroupOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateVolumeGroupOpts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVolumeGroupOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *CreateVolumeGroupOpts) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateVolumeGroupOpts) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

func (m *CreateVolumeGroupOpts) GetAddVolumes() []string {
	if m != nil {
		return m.AddVolumes
	}
	return nil
}

func (m *CreateVolumeGroupOpts) GetRemoveVolumes() []string {
	if m != nil {
		return m.RemoveVolumes
	}
	return nil
}

func (m *CreateVolumeGroupOpts) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *CreateVolumeGroupOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type UpdateVolumeGroupOpts struct {
	// The uuid of the volume group, optional when updating.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The driver of the volume group.
	DriverName string `protobuf:"bytes,2,opt,name=driverName" json:"driverName,omitempty"`
	// The addVolumes contain UUIDs of volumes to be added to the group.
	AddVolumes []string `protobuf:"bytes,3,rep,name=addVolumes" json:"addVolumes,omitempty"`
	// The removeVolumes contains the volumes to be removed from the group.
	RemoveVolumes []string `protobuf:"bytes,4,rep,name=removeVolumes" json:"removeVolumes,omitempty"`
	// The Context
	Context string `protobuf:"bytes,5,opt,name=context" json:"context,omitempty"`
}

func (m *UpdateVolumeGroupOpts) Reset()                    { *m = UpdateVolumeGroupOpts{} }
func (m *UpdateVolumeGroupOpts) String() string            { return proto1.CompactTextString(m) }
func (*UpdateVolumeGroupOpts) ProtoMessage()               {}
func (*UpdateVolumeGroupOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateVolumeGroupOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateVolumeGroupOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *UpdateVolumeGroupOpts) GetAddVolumes() []string {
	if m != nil {
		return m.AddVolumes
	}
	return nil
}

func (m *UpdateVolumeGroupOpts) GetRemoveVolumes() []string {
	if m != nil {
		return m.RemoveVolumes
	}
	return nil
}

func (m *UpdateVolumeGroupOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type DeleteVolumeGroupOpts struct {
	// The uuid of the volume group, optional when deleting.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The driver of the volume group.
	DriverName string `protobuf:"bytes,2,opt,name=driverName" json:"driverName,omitempty"`
	// The Context
	Context string `protobuf:"bytes,3,opt,name=context" json:"context,omitempty"`
}

func (m *DeleteVolumeGroupOpts) Reset()                    { *m = DeleteVolumeGroupOpts{} }
func (m *DeleteVolumeGroupOpts) String() string            { return proto1.CompactTextString(m) }
func (*DeleteVolumeGroupOpts) ProtoMessage()               {}
func (*DeleteVolumeGroupOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteVolumeGroupOpts) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteVolumeGroupOpts) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *DeleteVolumeGroupOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// AttachVolumeOpts is a structure which indicates all required
// properties for attaching a volume.
type AttachVolumeOpts struct {
	// The access protocol for attaching a volume.
	AccessProtocol string `protobuf:"bytes,1,opt,name=accessProtocol" json:"accessProtocol,omitempty"`
	// The connectionData for attaching a volume.
	ConnectionData string `protobuf:"bytes,2,opt,name=connectionData" json:"connectionData,omitempty"`
	// The metadata for attaching a volume, optional.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The Context
	Context string `protobuf:"bytes,4,opt,name=context" json:"context,omitempty"`
}

func (m *AttachVolumeOpts) Reset()                    { *m = AttachVolumeOpts{} }
func (m *AttachVolumeOpts) String() string            { return proto1.CompactTextString(m) }
func (*AttachVolumeOpts) ProtoMessage()               {}
func (*AttachVolumeOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AttachVolumeOpts) GetAccessProtocol() string {
	if m != nil {
		return m.AccessProtocol
	}
	return ""
}

func (m *AttachVolumeOpts) GetConnectionData() string {
	if m != nil {
		return m.ConnectionData
	}
	return ""
}

func (m *AttachVolumeOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AttachVolumeOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// DetachVolumeOpts is a structure which indicates all required
// properties for detaching a volume.
type DetachVolumeOpts struct {
	// The access protocol for detaching a volume.
	AccessProtocol string `protobuf:"bytes,1,opt,name=accessProtocol" json:"accessProtocol,omitempty"`
	// The connectionData for detaching a volume.
	ConnectionData string `protobuf:"bytes,2,opt,name=connectionData" json:"connectionData,omitempty"`
	// The metadata for detaching a volume, optional.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The Context
	Context string `protobuf:"bytes,4,opt,name=context" json:"context,omitempty"`
}

func (m *DetachVolumeOpts) Reset()                    { *m = DetachVolumeOpts{} }
func (m *DetachVolumeOpts) String() string            { return proto1.CompactTextString(m) }
func (*DetachVolumeOpts) ProtoMessage()               {}
func (*DetachVolumeOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DetachVolumeOpts) GetAccessProtocol() string {
	if m != nil {
		return m.AccessProtocol
	}
	return ""
}

func (m *DetachVolumeOpts) GetConnectionData() string {
	if m != nil {
		return m.ConnectionData
	}
	return ""
}

func (m *DetachVolumeOpts) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DetachVolumeOpts) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

// Generic response, it return:
// 1. Return result with message when create/update resource successfully.
// 2. Return result without message when delete resource successfully.
// 3. Return Error with error code and message when operate unsuccessfully.
type GenericResponse struct {
	// Types that are valid to be assigned to Reply:
	//	*GenericResponse_Result_
	//	*GenericResponse_Error_
	Reply isGenericResponse_Reply `protobuf_oneof:"reply"`
}

func (m *GenericResponse) Reset()                    { *m = GenericResponse{} }
func (m *GenericResponse) String() string            { return proto1.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()               {}
func (*GenericResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type isGenericResponse_Reply interface {
	isGenericResponse_Reply()
}

type GenericResponse_Result_ struct {
	Result *GenericResponse_Result `protobuf:"bytes,1,opt,name=result,oneof"`
}
type GenericResponse_Error_ struct {
	Error *GenericResponse_Error `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*GenericResponse_Result_) isGenericResponse_Reply() {}
func (*GenericResponse_Error_) isGenericResponse_Reply()  {}

func (m *GenericResponse) GetReply() isGenericResponse_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *GenericResponse) GetResult() *GenericResponse_Result {
	if x, ok := m.GetReply().(*GenericResponse_Result_); ok {
		return x.Result
	}
	return nil
}

func (m *GenericResponse) GetError() *GenericResponse_Error {
	if x, ok := m.GetReply().(*GenericResponse_Error_); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GenericResponse) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _GenericResponse_OneofMarshaler, _GenericResponse_OneofUnmarshaler, _GenericResponse_OneofSizer, []interface{}{
		(*GenericResponse_Result_)(nil),
		(*GenericResponse_Error_)(nil),
	}
}

func _GenericResponse_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*GenericResponse)
	// reply
	switch x := m.Reply.(type) {
	case *GenericResponse_Result_:
		b.EncodeVarint(1<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Result); err != nil {
			return err
		}
	case *GenericResponse_Error_:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GenericResponse.Reply has unexpected type %T", x)
	}
	return nil
}

func _GenericResponse_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*GenericResponse)
	switch tag {
	case 1: // reply.result
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(GenericResponse_Result)
		err := b.DecodeMessage(msg)
		m.Reply = &GenericResponse_Result_{msg}
		return true, err
	case 2: // reply.error
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(GenericResponse_Error)
		err := b.DecodeMessage(msg)
		m.Reply = &GenericResponse_Error_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GenericResponse_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*GenericResponse)
	// reply
	switch x := m.Reply.(type) {
	case *GenericResponse_Result_:
		s := proto1.Size(x.Result)
		n += proto1.SizeVarint(1<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *GenericResponse_Error_:
		s := proto1.Size(x.Error)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GenericResponse_Result struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *GenericResponse_Result) Reset()                    { *m = GenericResponse_Result{} }
func (m *GenericResponse_Result) String() string            { return proto1.CompactTextString(m) }
func (*GenericResponse_Result) ProtoMessage()               {}
func (*GenericResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13, 0} }

func (m *GenericResponse_Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GenericResponse_Error struct {
	Code        string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *GenericResponse_Error) Reset()                    { *m = GenericResponse_Error{} }
func (m *GenericResponse_Error) String() string            { return proto1.CompactTextString(m) }
func (*GenericResponse_Error) ProtoMessage()               {}
func (*GenericResponse_Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13, 1} }

func (m *GenericResponse_Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GenericResponse_Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto1.RegisterType((*CreateVolumeOpts)(nil), "proto.CreateVolumeOpts")
	proto1.RegisterType((*DeleteVolumeOpts)(nil), "proto.DeleteVolumeOpts")
	proto1.RegisterType((*ExtendVolumeOpts)(nil), "proto.ExtendVolumeOpts")
	proto1.RegisterType((*CreateVolumeSnapshotOpts)(nil), "proto.CreateVolumeSnapshotOpts")
	proto1.RegisterType((*DeleteVolumeSnapshotOpts)(nil), "proto.DeleteVolumeSnapshotOpts")
	proto1.RegisterType((*CreateAttachmentOpts)(nil), "proto.CreateAttachmentOpts")
	proto1.RegisterType((*DeleteAttachmentOpts)(nil), "proto.DeleteAttachmentOpts")
	proto1.RegisterType((*HostInfo)(nil), "proto.HostInfo")
	proto1.RegisterType((*CreateVolumeGroupOpts)(nil), "proto.CreateVolumeGroupOpts")
	proto1.RegisterType((*UpdateVolumeGroupOpts)(nil), "proto.UpdateVolumeGroupOpts")
	proto1.RegisterType((*DeleteVolumeGroupOpts)(nil), "proto.DeleteVolumeGroupOpts")
	proto1.RegisterType((*AttachVolumeOpts)(nil), "proto.AttachVolumeOpts")
	proto1.RegisterType((*DetachVolumeOpts)(nil), "proto.DetachVolumeOpts")
	proto1.RegisterType((*GenericResponse)(nil), "proto.GenericResponse")
	proto1.RegisterType((*GenericResponse_Result)(nil), "proto.GenericResponse.Result")
	proto1.RegisterType((*GenericResponse_Error)(nil), "proto.GenericResponse.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProvisionDock service

type ProvisionDockClient interface {
	// Create a volume
	CreateVolume(ctx context.Context, in *CreateVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Delete a volume
	DeleteVolume(ctx context.Context, in *DeleteVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Extend a volume
	ExtendVolume(ctx context.Context, in *ExtendVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Create a volume snapshot
	CreateVolumeSnapshot(ctx context.Context, in *CreateVolumeSnapshotOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Delete a volume snapshot
	DeleteVolumeSnapshot(ctx context.Context, in *DeleteVolumeSnapshotOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Create a volume attachment
	CreateAttachment(ctx context.Context, in *CreateAttachmentOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Delete a volume attachment
	DeleteAttachment(ctx context.Context, in *DeleteAttachmentOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Create a volume group
	CreateVolumeGroup(ctx context.Context, in *CreateVolumeGroupOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Update volume group
	UpdateVolumeGroup(ctx context.Context, in *UpdateVolumeGroupOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Delete volume group
	DeleteVolumeGroup(ctx context.Context, in *DeleteVolumeGroupOpts, opts ...grpc.CallOption) (*GenericResponse, error)
}

type provisionDockClient struct {
	cc *grpc.ClientConn
}

func NewProvisionDockClient(cc *grpc.ClientConn) ProvisionDockClient {
	return &provisionDockClient{cc}
}

func (c *provisionDockClient) CreateVolume(ctx context.Context, in *CreateVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/CreateVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) DeleteVolume(ctx context.Context, in *DeleteVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/DeleteVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) ExtendVolume(ctx context.Context, in *ExtendVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/ExtendVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) CreateVolumeSnapshot(ctx context.Context, in *CreateVolumeSnapshotOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/CreateVolumeSnapshot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) DeleteVolumeSnapshot(ctx context.Context, in *DeleteVolumeSnapshotOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/DeleteVolumeSnapshot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) CreateAttachment(ctx context.Context, in *CreateAttachmentOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/CreateAttachment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) DeleteAttachment(ctx context.Context, in *DeleteAttachmentOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/DeleteAttachment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) CreateVolumeGroup(ctx context.Context, in *CreateVolumeGroupOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/CreateVolumeGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) UpdateVolumeGroup(ctx context.Context, in *UpdateVolumeGroupOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/UpdateVolumeGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionDockClient) DeleteVolumeGroup(ctx context.Context, in *DeleteVolumeGroupOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.ProvisionDock/DeleteVolumeGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProvisionDock service

type ProvisionDockServer interface {
	// Create a volume
	CreateVolume(context.Context, *CreateVolumeOpts) (*GenericResponse, error)
	// Delete a volume
	DeleteVolume(context.Context, *DeleteVolumeOpts) (*GenericResponse, error)
	// Extend a volume
	ExtendVolume(context.Context, *ExtendVolumeOpts) (*GenericResponse, error)
	// Create a volume snapshot
	CreateVolumeSnapshot(context.Context, *CreateVolumeSnapshotOpts) (*GenericResponse, error)
	// Delete a volume snapshot
	DeleteVolumeSnapshot(context.Context, *DeleteVolumeSnapshotOpts) (*GenericResponse, error)
	// Create a volume attachment
	CreateAttachment(context.Context, *CreateAttachmentOpts) (*GenericResponse, error)
	// Delete a volume attachment
	DeleteAttachment(context.Context, *DeleteAttachmentOpts) (*GenericResponse, error)
	// Create a volume group
	CreateVolumeGroup(context.Context, *CreateVolumeGroupOpts) (*GenericResponse, error)
	// Update volume group
	UpdateVolumeGroup(context.Context, *UpdateVolumeGroupOpts) (*GenericResponse, error)
	// Delete volume group
	DeleteVolumeGroup(context.Context, *DeleteVolumeGroupOpts) (*GenericResponse, error)
}

func RegisterProvisionDockServer(s *grpc.Server, srv ProvisionDockServer) {
	s.RegisterService(&_ProvisionDock_serviceDesc, srv)
}

func _ProvisionDock_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/CreateVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).CreateVolume(ctx, req.(*CreateVolumeOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/DeleteVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).DeleteVolume(ctx, req.(*DeleteVolumeOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_ExtendVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendVolumeOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).ExtendVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/ExtendVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).ExtendVolume(ctx, req.(*ExtendVolumeOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_CreateVolumeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeSnapshotOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).CreateVolumeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/CreateVolumeSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).CreateVolumeSnapshot(ctx, req.(*CreateVolumeSnapshotOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_DeleteVolumeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeSnapshotOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).DeleteVolumeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/DeleteVolumeSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).DeleteVolumeSnapshot(ctx, req.(*DeleteVolumeSnapshotOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_CreateAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttachmentOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).CreateAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/CreateAttachment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).CreateAttachment(ctx, req.(*CreateAttachmentOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_DeleteAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttachmentOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).DeleteAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/DeleteAttachment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).DeleteAttachment(ctx, req.(*DeleteAttachmentOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_CreateVolumeGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeGroupOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).CreateVolumeGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/CreateVolumeGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).CreateVolumeGroup(ctx, req.(*CreateVolumeGroupOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_UpdateVolumeGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVolumeGroupOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).UpdateVolumeGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/UpdateVolumeGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).UpdateVolumeGroup(ctx, req.(*UpdateVolumeGroupOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionDock_DeleteVolumeGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeGroupOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionDockServer).DeleteVolumeGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionDock/DeleteVolumeGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionDockServer).DeleteVolumeGroup(ctx, req.(*DeleteVolumeGroupOpts))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProvisionDock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProvisionDock",
	HandlerType: (*ProvisionDockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolume",
			Handler:    _ProvisionDock_CreateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _ProvisionDock_DeleteVolume_Handler,
		},
		{
			MethodName: "ExtendVolume",
			Handler:    _ProvisionDock_ExtendVolume_Handler,
		},
		{
			MethodName: "CreateVolumeSnapshot",
			Handler:    _ProvisionDock_CreateVolumeSnapshot_Handler,
		},
		{
			MethodName: "DeleteVolumeSnapshot",
			Handler:    _ProvisionDock_DeleteVolumeSnapshot_Handler,
		},
		{
			MethodName: "CreateAttachment",
			Handler:    _ProvisionDock_CreateAttachment_Handler,
		},
		{
			MethodName: "DeleteAttachment",
			Handler:    _ProvisionDock_DeleteAttachment_Handler,
		},
		{
			MethodName: "CreateVolumeGroup",
			Handler:    _ProvisionDock_CreateVolumeGroup_Handler,
		},
		{
			MethodName: "UpdateVolumeGroup",
			Handler:    _ProvisionDock_UpdateVolumeGroup_Handler,
		},
		{
			MethodName: "DeleteVolumeGroup",
			Handler:    _ProvisionDock_DeleteVolumeGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dock.proto",
}

// Client API for AttachDock service

type AttachDockClient interface {
	// Attach a volume
	AttachVolume(ctx context.Context, in *AttachVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error)
	// Detach a volume
	DetachVolume(ctx context.Context, in *DetachVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error)
}

type attachDockClient struct {
	cc *grpc.ClientConn
}

func NewAttachDockClient(cc *grpc.ClientConn) AttachDockClient {
	return &attachDockClient{cc}
}

func (c *attachDockClient) AttachVolume(ctx context.Context, in *AttachVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.AttachDock/AttachVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attachDockClient) DetachVolume(ctx context.Context, in *DetachVolumeOpts, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/proto.AttachDock/DetachVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AttachDock service

type AttachDockServer interface {
	// Attach a volume
	AttachVolume(context.Context, *AttachVolumeOpts) (*GenericResponse, error)
	// Detach a volume
	DetachVolume(context.Context, *DetachVolumeOpts) (*GenericResponse, error)
}

func RegisterAttachDockServer(s *grpc.Server, srv AttachDockServer) {
	s.RegisterService(&_AttachDock_serviceDesc, srv)
}

func _AttachDock_AttachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachVolumeOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachDockServer).AttachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AttachDock/AttachVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachDockServer).AttachVolume(ctx, req.(*AttachVolumeOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttachDock_DetachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachVolumeOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachDockServer).DetachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AttachDock/DetachVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachDockServer).DetachVolume(ctx, req.(*DetachVolumeOpts))
	}
	return interceptor(ctx, in, info, handler)
}

var _AttachDock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AttachDock",
	HandlerType: (*AttachDockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttachVolume",
			Handler:    _AttachDock_AttachVolume_Handler,
		},
		{
			MethodName: "DetachVolume",
			Handler:    _AttachDock_DetachVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dock.proto",
}

func init() { proto1.RegisterFile("dock.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1039 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xae, 0xed, 0x38, 0x71, 0xde, 0x6c, 0x77, 0xc3, 0xa8, 0x5d, 0xac, 0x50, 0x96, 0x2a, 0x02,
	0x54, 0x40, 0xf4, 0x10, 0x90, 0x40, 0x20, 0x0e, 0x85, 0xad, 0xb6, 0x11, 0x5f, 0xc5, 0x7c, 0x1c,
	0xb8, 0xcd, 0xda, 0x53, 0x6a, 0xd5, 0xf1, 0x58, 0xe3, 0x49, 0xb4, 0xe1, 0xc4, 0x91, 0x33, 0xff,
	0x80, 0x13, 0x27, 0xfe, 0x05, 0xbf, 0x80, 0x33, 0x3f, 0x81, 0x0b, 0x67, 0xf6, 0x80, 0x66, 0xfc,
	0x91, 0xb1, 0x63, 0x4f, 0xb2, 0xd0, 0x85, 0x1e, 0x38, 0x75, 0xe6, 0xf5, 0xeb, 0x67, 0xfc, 0x3c,
	0xf3, 0x7e, 0xa5, 0x00, 0x01, 0xf5, 0xaf, 0x8e, 0x13, 0x46, 0x39, 0x45, 0xb6, 0xfc, 0x33, 0xfe,
	0xc5, 0x82, 0xe1, 0x07, 0x8c, 0x60, 0x4e, 0xbe, 0xa2, 0xd1, 0x7c, 0x46, 0x3e, 0x4d, 0x78, 0x8a,
	0x6e, 0x83, 0x19, 0x06, 0xae, 0x71, 0x68, 0x1c, 0xf5, 0x3d, 0x33, 0x0c, 0x10, 0x82, 0x4e, 0x8c,
	0x67, 0xc4, 0x35, 0xa5, 0x45, 0xae, 0x85, 0x2d, 0x0d, 0xbf, 0x25, 0xae, 0x75, 0x68, 0x1c, 0x59,
	0x9e, 0x5c, 0xa3, 0x43, 0x18, 0x04, 0x24, 0xf5, 0x59, 0x98, 0xf0, 0x90, 0xc6, 0x6e, 0x47, 0xba,
	0xab, 0x26, 0x74, 0x0f, 0x20, 0x8d, 0x71, 0x92, 0x5e, 0x52, 0x3e, 0x0d, 0x5c, 0x5b, 0x3a, 0x28,
	0x16, 0xf4, 0x2a, 0x0c, 0xf1, 0x02, 0x87, 0x11, 0x7e, 0x18, 0x46, 0x21, 0x5f, 0x7e, 0x4d, 0x63,
	0xe2, 0x76, 0xa5, 0xd7, 0x9a, 0x1d, 0x1d, 0x40, 0x3f, 0x61, 0xf4, 0x22, 0x8c, 0xc8, 0x34, 0x70,
	0x7b, 0xd2, 0x69, 0x65, 0x40, 0x77, 0xa1, 0x9b, 0x50, 0x1a, 0x4d, 0x03, 0xd7, 0x91, 0x8f, 0xf2,
	0x1d, 0x1a, 0x81, 0x23, 0x56, 0x9f, 0x08, 0x3e, 0x7d, 0xf9, 0xa4, 0xdc, 0xa3, 0x13, 0x70, 0x66,
	0x84, 0xe3, 0x00, 0x73, 0xec, 0xc2, 0xa1, 0x75, 0x34, 0x98, 0xbc, 0x94, 0xa9, 0x75, 0x5c, 0x97,
	0xe8, 0xf8, 0xe3, 0xdc, 0xef, 0x34, 0xe6, 0x6c, 0xe9, 0x95, 0xaf, 0x09, 0x82, 0x01, 0x0b, 0x17,
	0x84, 0xc9, 0x03, 0x06, 0x19, 0xc1, 0x95, 0x05, 0xb9, 0xd0, 0xf3, 0x69, 0xcc, 0xc9, 0x23, 0xee,
	0xde, 0x92, 0x0f, 0x8b, 0xed, 0xe8, 0x5d, 0xd8, 0xad, 0x80, 0xa2, 0x21, 0x58, 0x57, 0x64, 0x99,
	0x5f, 0x83, 0x58, 0xa2, 0x3d, 0xb0, 0x17, 0x38, 0x9a, 0x17, 0x17, 0x91, 0x6d, 0xde, 0x31, 0xdf,
	0x36, 0xc6, 0xbf, 0x19, 0x30, 0xbc, 0x4f, 0x22, 0xa2, 0xbd, 0x46, 0x95, 0x9e, 0x59, 0xa1, 0x57,
	0x7f, 0x75, 0x4b, 0x7a, 0x96, 0x8e, 0x5e, 0xe7, 0x1a, 0xe9, 0x89, 0x28, 0x3d, 0x7d, 0xc4, 0x49,
	0x1c, 0xfc, 0x1f, 0xa5, 0x9a, 0x28, 0xad, 0x4b, 0x74, 0xd3, 0xa2, 0xf4, 0x57, 0x13, 0x5c, 0x35,
	0x93, 0x3e, 0xcf, 0x25, 0x7d, 0xca, 0xd7, 0x39, 0x02, 0x67, 0x21, 0xcf, 0x2b, 0x2f, 0xb3, 0xdc,
	0xa3, 0xa9, 0x22, 0x66, 0x57, 0x8a, 0xf9, 0x7a, 0x43, 0xca, 0xab, 0x1f, 0xba, 0xa5, 0xa8, 0x3d,
	0x9d, 0xa8, 0xce, 0x35, 0x8a, 0xfa, 0xbd, 0x09, 0xae, 0x9a, 0xbf, 0x5a, 0x51, 0x55, 0x29, 0x4c,
	0x8d, 0x14, 0x56, 0x45, 0x8a, 0x36, 0xf8, 0x2d, 0xa5, 0xe8, 0xe8, 0xa4, 0xb0, 0xaf, 0x51, 0x8a,
	0x3f, 0x4c, 0xd8, 0xcb, 0xae, 0xed, 0x84, 0x73, 0xec, 0x5f, 0xce, 0x48, 0xfc, 0xe4, 0x32, 0xbc,
	0x08, 0xbb, 0x01, 0xfd, 0x88, 0xfa, 0x38, 0xca, 0x40, 0x64, 0xb0, 0x39, 0x5e, 0xd5, 0x28, 0xd2,
	0x7a, 0x36, 0x8f, 0x78, 0x78, 0x8e, 0xf9, 0xa5, 0x24, 0xe8, 0x78, 0x2b, 0x03, 0x7a, 0x0d, 0x9c,
	0x4b, 0x9a, 0xf2, 0x69, 0x7c, 0x41, 0x25, 0xc1, 0xc1, 0xe4, 0x4e, 0x2e, 0xe5, 0x59, 0x6e, 0xf6,
	0x4a, 0x07, 0x74, 0xba, 0x16, 0x82, 0xaf, 0x54, 0x42, 0xb0, 0xca, 0xe5, 0xa6, 0x85, 0xdf, 0xcf,
	0x26, 0xec, 0x65, 0xf1, 0xf1, 0x0f, 0x34, 0x57, 0xf5, 0xb2, 0x9e, 0x44, 0xaf, 0x4e, 0x45, 0xaf,
	0xa6, 0xef, 0xd8, 0x52, 0x2f, 0x5b, 0xa7, 0x57, 0xf7, 0x1a, 0xf5, 0xfa, 0xce, 0x00, 0xa7, 0x20,
	0x25, 0xcb, 0x7c, 0x84, 0xf9, 0x05, 0x65, 0xb3, 0xfc, 0xed, 0x72, 0x2f, 0x5a, 0x03, 0x4d, 0xbf,
	0x58, 0x26, 0x05, 0x46, 0xbe, 0x13, 0x35, 0x50, 0x48, 0x91, 0x37, 0x5f, 0xb9, 0x96, 0x5a, 0x27,
	0x79, 0x9e, 0x99, 0x61, 0x22, 0xa2, 0x33, 0x8c, 0x43, 0x1e, 0x62, 0x4e, 0x59, 0x4e, 0x6d, 0x65,
	0x18, 0xff, 0x68, 0xc2, 0xbe, 0x5a, 0xdd, 0x1e, 0x30, 0x3a, 0x4f, 0xb6, 0xae, 0xc1, 0x9b, 0x46,
	0x80, 0xcd, 0xf5, 0xb8, 0xa9, 0x7d, 0xda, 0x2d, 0xed, 0xf3, 0x1e, 0x00, 0x0e, 0xf2, 0x96, 0x96,
	0xca, 0xf4, 0xe8, 0x7b, 0x8a, 0x45, 0x64, 0x2b, 0x23, 0x33, 0xba, 0x20, 0x85, 0x4b, 0x4f, 0xba,
	0x54, 0x8d, 0xad, 0x6d, 0x56, 0xb9, 0xe3, 0x7e, 0xe5, 0x8e, 0xc7, 0x3f, 0x19, 0xb0, 0xff, 0x65,
	0x12, 0x6c, 0xa1, 0x51, 0x55, 0x0f, 0x73, 0x4d, 0x8f, 0x2a, 0x03, 0x6b, 0x33, 0x83, 0x4e, 0x13,
	0x83, 0xd6, 0x8a, 0x39, 0xc6, 0xb0, 0xaf, 0xd6, 0xe7, 0xbf, 0xff, 0xa1, 0xca, 0x11, 0x56, 0xf5,
	0x88, 0xc7, 0x06, 0x0c, 0xb3, 0xac, 0x52, 0xc6, 0xaf, 0x97, 0xe1, 0x36, 0xf6, 0x7d, 0x92, 0xa6,
	0xe7, 0x22, 0xf7, 0x7c, 0x1a, 0xe5, 0x47, 0xd5, 0xac, 0xc2, 0xcf, 0xa7, 0x71, 0x4c, 0x7c, 0x71,
	0xf7, 0xf7, 0xb3, 0xd9, 0x53, 0xfa, 0x55, 0xad, 0x95, 0xb1, 0xc6, 0xaa, 0x8c, 0x35, 0xf5, 0xa3,
	0x5b, 0x53, 0xfa, 0x29, 0x4d, 0x9f, 0x8f, 0xe5, 0x70, 0xfd, 0x9f, 0xd1, 0xaf, 0x1f, 0xfd, 0x6f,
	0xd3, 0xff, 0xdd, 0x80, 0x3b, 0x0f, 0x48, 0x4c, 0x58, 0xe8, 0x7b, 0x24, 0x4d, 0x68, 0x9c, 0x12,
	0xf4, 0x16, 0x74, 0x19, 0x49, 0xe7, 0x11, 0x97, 0x10, 0x83, 0xc9, 0xf3, 0xf9, 0xb7, 0xd6, 0xfc,
	0x8e, 0x3d, 0xe9, 0x74, 0xb6, 0xe3, 0xe5, 0xee, 0xe8, 0x4d, 0xb0, 0x09, 0x63, 0x94, 0xc9, 0x63,
	0x06, 0x93, 0x83, 0x96, 0xf7, 0x4e, 0x85, 0xcf, 0xd9, 0x8e, 0x97, 0x39, 0x8f, 0xc6, 0xd0, 0xcd,
	0x90, 0x04, 0xc7, 0x19, 0x49, 0x53, 0xfc, 0x0d, 0xc9, 0x3f, 0xbe, 0xd8, 0x8e, 0xde, 0x03, 0x5b,
	0xbe, 0x25, 0x8a, 0x96, 0x4f, 0x83, 0xe2, 0xb9, 0x5c, 0xd7, 0x8b, 0x92, 0xb9, 0x56, 0x94, 0xde,
	0xef, 0x81, 0xcd, 0x48, 0x12, 0x2d, 0x27, 0x7f, 0xda, 0xb0, 0x7b, 0xce, 0xe8, 0x22, 0x4c, 0xc5,
	0xd5, 0x50, 0xff, 0x0a, 0x9d, 0xc0, 0x2d, 0xb5, 0x5c, 0xa2, 0x67, 0x5b, 0x7e, 0x14, 0x8e, 0xee,
	0x36, 0xb3, 0x19, 0xef, 0x08, 0x08, 0x35, 0x49, 0x4b, 0x88, 0xfa, 0x0f, 0x2f, 0x3d, 0x84, 0x3a,
	0xdf, 0x97, 0x10, 0xf5, 0xa1, 0x5f, 0x03, 0xf1, 0x59, 0x31, 0x1e, 0x55, 0x47, 0x39, 0xf4, 0xc2,
	0x86, 0x91, 0x57, 0x0f, 0xd9, 0x34, 0x1d, 0x96, 0x90, 0x6d, 0xa3, 0xa3, 0x06, 0x72, 0x5a, 0xfc,
	0x47, 0x62, 0xd5, 0xc8, 0xd1, 0x73, 0x9a, 0x89, 0x48, 0x0f, 0x55, 0x9f, 0x09, 0x4a, 0xa8, 0xa6,
	0x61, 0x41, 0x03, 0xf5, 0x21, 0x3c, 0xb3, 0xd6, 0x33, 0xd1, 0x41, 0x83, 0x70, 0x65, 0x01, 0xd6,
	0x83, 0xad, 0x35, 0x97, 0x12, 0xac, 0xb1, 0xed, 0xe8, 0xc1, 0xd6, 0x1a, 0x40, 0x09, 0xd6, 0xd8,
	0x1a, 0xda, 0xc1, 0x26, 0x3f, 0x18, 0x00, 0x99, 0x26, 0x45, 0xe8, 0xab, 0xd5, 0xb7, 0x0c, 0xba,
	0x7a, 0x49, 0xde, 0x14, 0xfa, 0x0d, 0x10, 0xf5, 0xb2, 0xd6, 0x0e, 0xf1, 0xb0, 0x2b, 0x1f, 0xbc,
	0xf1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x4e, 0x51, 0xc9, 0xc0, 0x12, 0x00, 0x00,
}
