package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/opensds/opensds/api/openapi-spec/models"
)

// NewUpdateVolumeParams creates a new UpdateVolumeParams object
// with the default values initialized.
func NewUpdateVolumeParams() *UpdateVolumeParams {
	var ()
	return &UpdateVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateVolumeParamsWithTimeout creates a new UpdateVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateVolumeParamsWithTimeout(timeout time.Duration) *UpdateVolumeParams {
	var ()
	return &UpdateVolumeParams{

		timeout: timeout,
	}
}

// NewUpdateVolumeParamsWithContext creates a new UpdateVolumeParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateVolumeParamsWithContext(ctx context.Context) *UpdateVolumeParams {
	var ()
	return &UpdateVolumeParams{

		Context: ctx,
	}
}

// NewUpdateVolumeParamsWithHTTPClient creates a new UpdateVolumeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateVolumeParamsWithHTTPClient(client *http.Client) *UpdateVolumeParams {
	var ()
	return &UpdateVolumeParams{
		HTTPClient: client,
	}
}

/*UpdateVolumeParams contains all the parameters to send to the API endpoint
for the update volume operation typically these are written to a http.Request
*/
type UpdateVolumeParams struct {

	/*ID
	  ID of specified volume

	*/
	ID string
	/*ResourceType
	  Type of specified volume backend resource

	*/
	ResourceType string
	/*VolumeRequest
	  Volume request object

	*/
	VolumeRequest *models.VolumeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update volume params
func (o *UpdateVolumeParams) WithTimeout(timeout time.Duration) *UpdateVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update volume params
func (o *UpdateVolumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update volume params
func (o *UpdateVolumeParams) WithContext(ctx context.Context) *UpdateVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update volume params
func (o *UpdateVolumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update volume params
func (o *UpdateVolumeParams) WithHTTPClient(client *http.Client) *UpdateVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update volume params
func (o *UpdateVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update volume params
func (o *UpdateVolumeParams) WithID(id string) *UpdateVolumeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update volume params
func (o *UpdateVolumeParams) SetID(id string) {
	o.ID = id
}

// WithResourceType adds the resourceType to the update volume params
func (o *UpdateVolumeParams) WithResourceType(resourceType string) *UpdateVolumeParams {
	o.SetResourceType(resourceType)
	return o
}

// SetResourceType adds the resourceType to the update volume params
func (o *UpdateVolumeParams) SetResourceType(resourceType string) {
	o.ResourceType = resourceType
}

// WithVolumeRequest adds the volumeRequest to the update volume params
func (o *UpdateVolumeParams) WithVolumeRequest(volumeRequest *models.VolumeRequest) *UpdateVolumeParams {
	o.SetVolumeRequest(volumeRequest)
	return o
}

// SetVolumeRequest adds the volumeRequest to the update volume params
func (o *UpdateVolumeParams) SetVolumeRequest(volumeRequest *models.VolumeRequest) {
	o.VolumeRequest = volumeRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param resourceType
	if err := r.SetPathParam("resourceType", o.ResourceType); err != nil {
		return err
	}

	if o.VolumeRequest == nil {
		o.VolumeRequest = new(models.VolumeRequest)
	}

	if err := r.SetBodyParam(o.VolumeRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
