package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/opensds/opensds/api/openapi-spec/models"
)

// NewUpdateShareParams creates a new UpdateShareParams object
// with the default values initialized.
func NewUpdateShareParams() *UpdateShareParams {
	var ()
	return &UpdateShareParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateShareParamsWithTimeout creates a new UpdateShareParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateShareParamsWithTimeout(timeout time.Duration) *UpdateShareParams {
	var ()
	return &UpdateShareParams{

		timeout: timeout,
	}
}

// NewUpdateShareParamsWithContext creates a new UpdateShareParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateShareParamsWithContext(ctx context.Context) *UpdateShareParams {
	var ()
	return &UpdateShareParams{

		Context: ctx,
	}
}

// NewUpdateShareParamsWithHTTPClient creates a new UpdateShareParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateShareParamsWithHTTPClient(client *http.Client) *UpdateShareParams {
	var ()
	return &UpdateShareParams{
		HTTPClient: client,
	}
}

/*UpdateShareParams contains all the parameters to send to the API endpoint
for the update share operation typically these are written to a http.Request
*/
type UpdateShareParams struct {

	/*ID
	  ID of specified share

	*/
	ID string
	/*ResourceType
	  Type of specified share backend resource

	*/
	ResourceType string
	/*ShareRequest
	  Share request object

	*/
	ShareRequest *models.ShareRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update share params
func (o *UpdateShareParams) WithTimeout(timeout time.Duration) *UpdateShareParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update share params
func (o *UpdateShareParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update share params
func (o *UpdateShareParams) WithContext(ctx context.Context) *UpdateShareParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update share params
func (o *UpdateShareParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update share params
func (o *UpdateShareParams) WithHTTPClient(client *http.Client) *UpdateShareParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update share params
func (o *UpdateShareParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update share params
func (o *UpdateShareParams) WithID(id string) *UpdateShareParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update share params
func (o *UpdateShareParams) SetID(id string) {
	o.ID = id
}

// WithResourceType adds the resourceType to the update share params
func (o *UpdateShareParams) WithResourceType(resourceType string) *UpdateShareParams {
	o.SetResourceType(resourceType)
	return o
}

// SetResourceType adds the resourceType to the update share params
func (o *UpdateShareParams) SetResourceType(resourceType string) {
	o.ResourceType = resourceType
}

// WithShareRequest adds the shareRequest to the update share params
func (o *UpdateShareParams) WithShareRequest(shareRequest *models.ShareRequest) *UpdateShareParams {
	o.SetShareRequest(shareRequest)
	return o
}

// SetShareRequest adds the shareRequest to the update share params
func (o *UpdateShareParams) SetShareRequest(shareRequest *models.ShareRequest) {
	o.ShareRequest = shareRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateShareParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param resourceType
	if err := r.SetPathParam("resourceType", o.ResourceType); err != nil {
		return err
	}

	if o.ShareRequest == nil {
		o.ShareRequest = new(models.ShareRequest)
	}

	if err := r.SetBodyParam(o.ShareRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
