#!/bin/bash

# Copyright (c) 2017 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

MODEL_PACKAGE=github.com/opensds/opensds/pkg/model
PROTOBUF_PACKAGE=github.com/opensds/opensds/pkg/dock/proto

n=1
for testpkg in $(go list ./osdsctl/... ./client/... ./pkg/... ./contrib/...); do
  test $testpkg == "$MODEL_PACKAGE" && continue
  test $testpkg == "$PROTOBUF_PACKAGE" && continue
  covpkg="${testpkg/"/testing"/}"
  go test -covermode count -coverprofile "testing_"$n.coverprofile -coverpkg $covpkg $testpkg 2>/dev/null
  n=$((n+1))
done

gocovmerge `ls *.coverprofile` > cover.out
rm *.coverprofile
