package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetShareParams creates a new GetShareParams object
// with the default values initialized.
func NewGetShareParams() *GetShareParams {
	var ()
	return &GetShareParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetShareParamsWithTimeout creates a new GetShareParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetShareParamsWithTimeout(timeout time.Duration) *GetShareParams {
	var ()
	return &GetShareParams{

		timeout: timeout,
	}
}

// NewGetShareParamsWithContext creates a new GetShareParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetShareParamsWithContext(ctx context.Context) *GetShareParams {
	var ()
	return &GetShareParams{

		Context: ctx,
	}
}

// NewGetShareParamsWithHTTPClient creates a new GetShareParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetShareParamsWithHTTPClient(client *http.Client) *GetShareParams {
	var ()
	return &GetShareParams{
		HTTPClient: client,
	}
}

/*GetShareParams contains all the parameters to send to the API endpoint
for the get share operation typically these are written to a http.Request
*/
type GetShareParams struct {

	/*ID
	  ID of specified share

	*/
	ID string
	/*ResourceType
	  Type of specified share backend resource

	*/
	ResourceType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get share params
func (o *GetShareParams) WithTimeout(timeout time.Duration) *GetShareParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get share params
func (o *GetShareParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get share params
func (o *GetShareParams) WithContext(ctx context.Context) *GetShareParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get share params
func (o *GetShareParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get share params
func (o *GetShareParams) WithHTTPClient(client *http.Client) *GetShareParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get share params
func (o *GetShareParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get share params
func (o *GetShareParams) WithID(id string) *GetShareParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get share params
func (o *GetShareParams) SetID(id string) {
	o.ID = id
}

// WithResourceType adds the resourceType to the get share params
func (o *GetShareParams) WithResourceType(resourceType string) *GetShareParams {
	o.SetResourceType(resourceType)
	return o
}

// SetResourceType adds the resourceType to the get share params
func (o *GetShareParams) SetResourceType(resourceType string) {
	o.ResourceType = resourceType
}

// WriteToRequest writes these params to a swagger request
func (o *GetShareParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param resourceType
	if err := r.SetPathParam("resourceType", o.ResourceType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
