package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ListVolumeResourcesReader is a Reader for the ListVolumeResources structure.
type ListVolumeResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListVolumeResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListVolumeResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListVolumeResourcesOK creates a ListVolumeResourcesOK with default headers values
func NewListVolumeResourcesOK() *ListVolumeResourcesOK {
	return &ListVolumeResourcesOK{}
}

/*ListVolumeResourcesOK handles this case with default header values.

OK
*/
type ListVolumeResourcesOK struct {
	Payload ListVolumeResourcesOKBody
}

func (o *ListVolumeResourcesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/volumes][%d] listVolumeResourcesOK  %+v", 200, o.Payload)
}

func (o *ListVolumeResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListVolumeResourcesOKBody list volume resources o k body
swagger:model ListVolumeResourcesOKBody
*/
type ListVolumeResourcesOKBody interface{}
