package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// VolumeRequest volume request
// swagger:model VolumeRequest
type VolumeRequest struct {

	// action type
	ActionType string `json:"actionType,omitempty"`

	// allow details
	AllowDetails *bool `json:"allowDetails,omitempty"`

	// attachment
	Attachment string `json:"attachment,omitempty"`

	// device
	Device string `json:"device,omitempty"`

	// fs type
	FsType string `json:"fsType,omitempty"`

	// host
	Host string `json:"host,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// mount dir
	MountDir string `json:"mountDir,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// resource type
	ResourceType string `json:"resourceType,omitempty"`

	// size
	Size int32 `json:"size,omitempty"`
}

// Validate validates this volume request
func (m *VolumeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
