// Code generated by protoc-gen-go.
// source: fake_opensds.proto
// DO NOT EDIT!

/*
Package fake_opensds is a generated protocol buffer package.

It is generated from these files:
	fake_opensds.proto

It has these top-level messages:
	VolumeRequest
	ShareRequest
	Response
*/
package fake_opensds

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The VolumeRequest message containing all properties of
// a volume request.
type VolumeRequest struct {
	ResoureType  string `protobuf:"bytes,1,opt,name=resoureType" json:"resoureType,omitempty"`
	Id           string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Size         int32  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	AllowDetails bool   `protobuf:"varint,5,opt,name=allowDetails" json:"allowDetails,omitempty"`
	Host         string `protobuf:"bytes,6,opt,name=host" json:"host,omitempty"`
	Device       string `protobuf:"bytes,7,opt,name=device" json:"device,omitempty"`
	Attachment   string `protobuf:"bytes,8,opt,name=attachment" json:"attachment,omitempty"`
	MountDir     string `protobuf:"bytes,9,opt,name=mountDir" json:"mountDir,omitempty"`
	FsType       string `protobuf:"bytes,10,opt,name=fsType" json:"fsType,omitempty"`
}

func (m *VolumeRequest) Reset()                    { *m = VolumeRequest{} }
func (m *VolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*VolumeRequest) ProtoMessage()               {}
func (*VolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VolumeRequest) GetResoureType() string {
	if m != nil {
		return m.ResoureType
	}
	return ""
}

func (m *VolumeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VolumeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VolumeRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *VolumeRequest) GetAllowDetails() bool {
	if m != nil {
		return m.AllowDetails
	}
	return false
}

func (m *VolumeRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *VolumeRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *VolumeRequest) GetAttachment() string {
	if m != nil {
		return m.Attachment
	}
	return ""
}

func (m *VolumeRequest) GetMountDir() string {
	if m != nil {
		return m.MountDir
	}
	return ""
}

func (m *VolumeRequest) GetFsType() string {
	if m != nil {
		return m.FsType
	}
	return ""
}

// The ShareRequest message containing all properties of
// a share request.
type ShareRequest struct {
	ResoureType  string `protobuf:"bytes,1,opt,name=resoureType" json:"resoureType,omitempty"`
	Id           string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Size         int32  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	ShareType    string `protobuf:"bytes,5,opt,name=shareType" json:"shareType,omitempty"`
	ShareProto   string `protobuf:"bytes,6,opt,name=shareProto" json:"shareProto,omitempty"`
	AllowDetails bool   `protobuf:"varint,7,opt,name=allowDetails" json:"allowDetails,omitempty"`
}

func (m *ShareRequest) Reset()                    { *m = ShareRequest{} }
func (m *ShareRequest) String() string            { return proto.CompactTextString(m) }
func (*ShareRequest) ProtoMessage()               {}
func (*ShareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ShareRequest) GetResoureType() string {
	if m != nil {
		return m.ResoureType
	}
	return ""
}

func (m *ShareRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShareRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShareRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ShareRequest) GetShareType() string {
	if m != nil {
		return m.ShareType
	}
	return ""
}

func (m *ShareRequest) GetShareProto() string {
	if m != nil {
		return m.ShareProto
	}
	return ""
}

func (m *ShareRequest) GetAllowDetails() bool {
	if m != nil {
		return m.AllowDetails
	}
	return false
}

// The Response message containing all properties of
// resource response.
type Response struct {
	Status  string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*VolumeRequest)(nil), "fake_opensds.VolumeRequest")
	proto.RegisterType((*ShareRequest)(nil), "fake_opensds.ShareRequest")
	proto.RegisterType((*Response)(nil), "fake_opensds.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// const _ = grpc.SupportPackageIsVersion4

// Client API for Orchestration service

type OrchestrationClient interface {
	// Create a volume
	CreateVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Get a volume
	GetVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// List all volumes
	ListVolumes(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Delete a volume
	DeleteVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Attach a volume
	AttachVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Detach a volume
	DetachVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Mount a volume
	MountVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Unmount a volume
	UnmountVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Create a share
	CreateShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error)
	// Get a share
	GetShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error)
	// List all shares
	ListShares(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error)
	// Delete a share
	DeleteShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error)
}

type orchestrationClient struct {
	cc *grpc.ClientConn
}

func NewOrchestrationClient(cc *grpc.ClientConn) OrchestrationClient {
	return &orchestrationClient{cc}
}

func (c *orchestrationClient) CreateVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/CreateVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) GetVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/GetVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) ListVolumes(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/ListVolumes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) DeleteVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/DeleteVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) AttachVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/AttachVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) DetachVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/DetachVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) MountVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/MountVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) UnmountVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/UnmountVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) CreateShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/CreateShare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) GetShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/GetShare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) ListShares(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/ListShares", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationClient) DeleteShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Orchestration/DeleteShare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Orchestration service

type OrchestrationServer interface {
	// Create a volume
	CreateVolume(context.Context, *VolumeRequest) (*Response, error)
	// Get a volume
	GetVolume(context.Context, *VolumeRequest) (*Response, error)
	// List all volumes
	ListVolumes(context.Context, *VolumeRequest) (*Response, error)
	// Delete a volume
	DeleteVolume(context.Context, *VolumeRequest) (*Response, error)
	// Attach a volume
	AttachVolume(context.Context, *VolumeRequest) (*Response, error)
	// Detach a volume
	DetachVolume(context.Context, *VolumeRequest) (*Response, error)
	// Mount a volume
	MountVolume(context.Context, *VolumeRequest) (*Response, error)
	// Unmount a volume
	UnmountVolume(context.Context, *VolumeRequest) (*Response, error)
	// Create a share
	CreateShare(context.Context, *ShareRequest) (*Response, error)
	// Get a share
	GetShare(context.Context, *ShareRequest) (*Response, error)
	// List all shares
	ListShares(context.Context, *ShareRequest) (*Response, error)
	// Delete a share
	DeleteShare(context.Context, *ShareRequest) (*Response, error)
}

func RegisterOrchestrationServer(s *grpc.Server, srv OrchestrationServer) {
	s.RegisterService(&_Orchestration_serviceDesc, srv)
}

func _Orchestration_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/CreateVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).CreateVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/GetVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).GetVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/ListVolumes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).ListVolumes(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/DeleteVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).DeleteVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_AttachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).AttachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/AttachVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).AttachVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_DetachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).DetachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/DetachVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).DetachVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_MountVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).MountVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/MountVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).MountVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_UnmountVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).UnmountVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/UnmountVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).UnmountVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_CreateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).CreateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/CreateShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).CreateShare(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_GetShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).GetShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/GetShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).GetShare(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_ListShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).ListShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/ListShares",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).ListShares(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestration_DeleteShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServer).DeleteShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Orchestration/DeleteShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServer).DeleteShare(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orchestration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fake_opensds.Orchestration",
	HandlerType: (*OrchestrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolume",
			Handler:    _Orchestration_CreateVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _Orchestration_GetVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _Orchestration_ListVolumes_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _Orchestration_DeleteVolume_Handler,
		},
		{
			MethodName: "AttachVolume",
			Handler:    _Orchestration_AttachVolume_Handler,
		},
		{
			MethodName: "DetachVolume",
			Handler:    _Orchestration_DetachVolume_Handler,
		},
		{
			MethodName: "MountVolume",
			Handler:    _Orchestration_MountVolume_Handler,
		},
		{
			MethodName: "UnmountVolume",
			Handler:    _Orchestration_UnmountVolume_Handler,
		},
		{
			MethodName: "CreateShare",
			Handler:    _Orchestration_CreateShare_Handler,
		},
		{
			MethodName: "GetShare",
			Handler:    _Orchestration_GetShare_Handler,
		},
		{
			MethodName: "ListShares",
			Handler:    _Orchestration_ListShares_Handler,
		},
		{
			MethodName: "DeleteShare",
			Handler:    _Orchestration_DeleteShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fake_opensds.proto",
}

// Client API for Dock service

type DockClient interface {
	// Create a volume
	CreateVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Get a volume
	GetVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// List all volumes
	ListVolumes(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Delete a volume
	DeleteVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Attach a volume
	AttachVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Detach a volume
	DetachVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Mount a volume
	MountVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Unmount a volume
	UnmountVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error)
	// Create a share
	CreateShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error)
	// Get a share
	GetShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error)
	// List all shares
	ListShares(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error)
	// Delete a share
	DeleteShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error)
}

type dockClient struct {
	cc *grpc.ClientConn
}

func NewDockClient(cc *grpc.ClientConn) DockClient {
	return &dockClient{cc}
}

func (c *dockClient) CreateVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/CreateVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) GetVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/GetVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) ListVolumes(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/ListVolumes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) DeleteVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/DeleteVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) AttachVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/AttachVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) DetachVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/DetachVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) MountVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/MountVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) UnmountVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/UnmountVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) CreateShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/CreateShare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) GetShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/GetShare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) ListShares(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/ListShares", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockClient) DeleteShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fake_opensds.Dock/DeleteShare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dock service

type DockServer interface {
	// Create a volume
	CreateVolume(context.Context, *VolumeRequest) (*Response, error)
	// Get a volume
	GetVolume(context.Context, *VolumeRequest) (*Response, error)
	// List all volumes
	ListVolumes(context.Context, *VolumeRequest) (*Response, error)
	// Delete a volume
	DeleteVolume(context.Context, *VolumeRequest) (*Response, error)
	// Attach a volume
	AttachVolume(context.Context, *VolumeRequest) (*Response, error)
	// Detach a volume
	DetachVolume(context.Context, *VolumeRequest) (*Response, error)
	// Mount a volume
	MountVolume(context.Context, *VolumeRequest) (*Response, error)
	// Unmount a volume
	UnmountVolume(context.Context, *VolumeRequest) (*Response, error)
	// Create a share
	CreateShare(context.Context, *ShareRequest) (*Response, error)
	// Get a share
	GetShare(context.Context, *ShareRequest) (*Response, error)
	// List all shares
	ListShares(context.Context, *ShareRequest) (*Response, error)
	// Delete a share
	DeleteShare(context.Context, *ShareRequest) (*Response, error)
}

func RegisterDockServer(s *grpc.Server, srv DockServer) {
	s.RegisterService(&_Dock_serviceDesc, srv)
}

func _Dock_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/CreateVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).CreateVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/GetVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).GetVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/ListVolumes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).ListVolumes(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/DeleteVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).DeleteVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_AttachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).AttachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/AttachVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).AttachVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_DetachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).DetachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/DetachVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).DetachVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_MountVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).MountVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/MountVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).MountVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_UnmountVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).UnmountVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/UnmountVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).UnmountVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_CreateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).CreateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/CreateShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).CreateShare(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_GetShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).GetShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/GetShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).GetShare(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_ListShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).ListShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/ListShares",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).ListShares(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dock_DeleteShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockServer).DeleteShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fake_opensds.Dock/DeleteShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockServer).DeleteShare(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fake_opensds.Dock",
	HandlerType: (*DockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolume",
			Handler:    _Dock_CreateVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _Dock_GetVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _Dock_ListVolumes_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _Dock_DeleteVolume_Handler,
		},
		{
			MethodName: "AttachVolume",
			Handler:    _Dock_AttachVolume_Handler,
		},
		{
			MethodName: "DetachVolume",
			Handler:    _Dock_DetachVolume_Handler,
		},
		{
			MethodName: "MountVolume",
			Handler:    _Dock_MountVolume_Handler,
		},
		{
			MethodName: "UnmountVolume",
			Handler:    _Dock_UnmountVolume_Handler,
		},
		{
			MethodName: "CreateShare",
			Handler:    _Dock_CreateShare_Handler,
		},
		{
			MethodName: "GetShare",
			Handler:    _Dock_GetShare_Handler,
		},
		{
			MethodName: "ListShares",
			Handler:    _Dock_ListShares_Handler,
		},
		{
			MethodName: "DeleteShare",
			Handler:    _Dock_DeleteShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fake_opensds.proto",
}

func init() { proto.RegisterFile("fake_opensds.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x96, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0x48, 0x1c, 0x67, 0x92, 0x70, 0x18, 0xa1, 0x6a, 0x15, 0x10, 0xaa, 0x7c, 0xe2,
	0xd4, 0x43, 0x79, 0x01, 0x68, 0x0d, 0x5c, 0x40, 0x20, 0xf3, 0xe7, 0x8a, 0x96, 0x64, 0x4a, 0xac,
	0xda, 0x5e, 0xb3, 0xb3, 0x06, 0xc1, 0x3b, 0xf0, 0x62, 0xbd, 0xf2, 0x42, 0xec, 0xae, 0x5d, 0xb0,
	0x55, 0x89, 0x43, 0x56, 0xea, 0x29, 0xb7, 0x9d, 0x6f, 0x36, 0xbf, 0xf8, 0x1b, 0x7f, 0x23, 0x19,
	0xf0, 0x42, 0x5e, 0xd2, 0x27, 0x55, 0x53, 0xc5, 0x5b, 0x3e, 0xa9, 0xb5, 0x32, 0x0a, 0x97, 0x7d,
	0x2d, 0xf9, 0x35, 0x86, 0xd5, 0x47, 0x55, 0x34, 0x25, 0x65, 0xf4, 0xb5, 0x21, 0x36, 0x78, 0x0c,
	0x0b, 0x4d, 0xac, 0x1a, 0x4d, 0xef, 0x7f, 0xd4, 0x24, 0x46, 0xc7, 0xa3, 0xc7, 0xf3, 0xac, 0x2f,
	0xe1, 0x3d, 0x18, 0xe7, 0x5b, 0x31, 0xf6, 0x0d, 0x7b, 0x42, 0x84, 0x49, 0x25, 0x4b, 0x12, 0x77,
	0xbd, 0xe2, 0xcf, 0x4e, 0xe3, 0xfc, 0x27, 0x89, 0x89, 0xd5, 0xa6, 0x99, 0x3f, 0x63, 0x02, 0x4b,
	0x59, 0x14, 0xea, 0x7b, 0x4a, 0x46, 0xe6, 0x05, 0x8b, 0xa9, 0xed, 0xc5, 0xd9, 0x40, 0x73, 0xbf,
	0xdb, 0x29, 0x36, 0x22, 0x6a, 0x59, 0xee, 0x8c, 0x47, 0x10, 0x6d, 0xe9, 0x5b, 0xbe, 0x21, 0x31,
	0xf3, 0x6a, 0x57, 0xe1, 0x23, 0x00, 0x69, 0x8c, 0xdc, 0xec, 0x4a, 0xaa, 0x8c, 0x88, 0x7d, 0xaf,
	0xa7, 0xe0, 0x1a, 0xe2, 0x52, 0x35, 0x95, 0x49, 0x73, 0x2d, 0xe6, 0xbe, 0xfb, 0xb7, 0x76, 0xcc,
	0x0b, 0xf6, 0x06, 0xa1, 0x65, 0xb6, 0x55, 0x72, 0x35, 0x82, 0xe5, 0xbb, 0x9d, 0xd4, 0xb7, 0x30,
	0x8e, 0x87, 0x30, 0x67, 0xf7, 0x4f, 0x9e, 0x3b, 0xf5, 0x97, 0xff, 0x09, 0xce, 0x9c, 0x2f, 0xde,
	0xba, 0x97, 0xd6, 0x8d, 0xa3, 0xa7, 0xdc, 0x18, 0xe6, 0xec, 0xe6, 0x30, 0x93, 0x0c, 0xe2, 0x8c,
	0xb8, 0x56, 0x15, 0x93, 0x33, 0xcc, 0x46, 0x9a, 0x86, 0x3b, 0x0b, 0x5d, 0x85, 0x02, 0x66, 0x25,
	0x31, 0xcb, 0x2f, 0xd4, 0x59, 0xb8, 0x2e, 0xf1, 0x3e, 0x4c, 0x49, 0x6b, 0xa5, 0x3b, 0x23, 0x6d,
	0x71, 0xfa, 0x3b, 0x82, 0xd5, 0x1b, 0xbd, 0xd9, 0xd9, 0xd9, 0x68, 0x69, 0x72, 0x55, 0xe1, 0x73,
	0x58, 0x9e, 0x6b, 0x92, 0x86, 0xda, 0x1c, 0xe1, 0x83, 0x93, 0x41, 0xea, 0x06, 0xe9, 0x5a, 0x1f,
	0x0d, 0x9b, 0xd7, 0x8f, 0x97, 0xdc, 0xc1, 0x33, 0x98, 0xbf, 0x24, 0x13, 0xc6, 0x48, 0x61, 0xf1,
	0x2a, 0xe7, 0x0e, 0xc2, 0xfb, 0x52, 0xac, 0xa1, 0x94, 0x0a, 0x0a, 0x35, 0x64, 0x31, 0xcf, 0x7c,
	0x18, 0x83, 0x31, 0xee, 0x7d, 0x86, 0x62, 0xec, 0x68, 0x5e, 0xbb, 0xf0, 0x87, 0x51, 0x5e, 0xc0,
	0xea, 0x43, 0x55, 0x86, 0x73, 0xce, 0x61, 0xd1, 0x66, 0xc6, 0xef, 0x1a, 0xae, 0x87, 0x17, 0xfb,
	0x0b, 0xf8, 0x1f, 0xc8, 0x53, 0x88, 0x6d, 0x62, 0x42, 0x08, 0x67, 0x00, 0x2e, 0x2f, 0xfe, 0x36,
	0xef, 0xc9, 0xb0, 0x56, 0xda, 0xb4, 0x04, 0x3c, 0xc8, 0xe9, 0x55, 0x04, 0x93, 0x54, 0x6d, 0x2e,
	0x0f, 0xcb, 0x74, 0x58, 0xa6, 0xc3, 0x32, 0x85, 0x2d, 0xd3, 0xe7, 0xc8, 0x7f, 0xe8, 0x3c, 0xf9,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xd2, 0xe7, 0x17, 0xfe, 0x08, 0x00, 0x00,
}
