// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VolumeGroupSpec Volume group contains a list of volumes that are used in the same application.
// swagger:model VolumeGroupSpec
type VolumeGroupSpec struct {
	BaseModel

	// availability zone
	// Required: true
	// Read Only: true
	AvailabilityZone string `json:"availabilityZone"`

	// description
	// Required: true
	Description *string `json:"description"`

	// name
	// Required: true
	Name *string `json:"name"`

	// pool Id
	// Read Only: true
	PoolID string `json:"poolId,omitempty"`

	// profiles
	// Required: true
	Profiles []string `json:"profiles"`

	// project Id
	// Required: true
	// Read Only: true
	ProjectID string `json:"projectId"`

	// status
	// Required: true
	// Read Only: true
	Status string `json:"status"`

	// user Id
	// Read Only: true
	UserID string `json:"userId,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *VolumeGroupSpec) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BaseModel
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BaseModel = aO0

	// AO1
	var dataAO1 struct {
		AvailabilityZone string `json:"availabilityZone"`

		Description *string `json:"description"`

		Name *string `json:"name"`

		PoolID string `json:"poolId,omitempty"`

		Profiles []string `json:"profiles"`

		ProjectID string `json:"projectId"`

		Status string `json:"status"`

		UserID string `json:"userId,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.AvailabilityZone = dataAO1.AvailabilityZone

	m.Description = dataAO1.Description

	m.Name = dataAO1.Name

	m.PoolID = dataAO1.PoolID

	m.Profiles = dataAO1.Profiles

	m.ProjectID = dataAO1.ProjectID

	m.Status = dataAO1.Status

	m.UserID = dataAO1.UserID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m VolumeGroupSpec) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BaseModel)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		AvailabilityZone string `json:"availabilityZone"`

		Description *string `json:"description"`

		Name *string `json:"name"`

		PoolID string `json:"poolId,omitempty"`

		Profiles []string `json:"profiles"`

		ProjectID string `json:"projectId"`

		Status string `json:"status"`

		UserID string `json:"userId,omitempty"`
	}

	dataAO1.AvailabilityZone = m.AvailabilityZone

	dataAO1.Description = m.Description

	dataAO1.Name = m.Name

	dataAO1.PoolID = m.PoolID

	dataAO1.Profiles = m.Profiles

	dataAO1.ProjectID = m.ProjectID

	dataAO1.Status = m.Status

	dataAO1.UserID = m.UserID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this volume group spec
func (m *VolumeGroupSpec) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BaseModel
	if err := m.BaseModel.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAvailabilityZone(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfiles(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VolumeGroupSpec) validateAvailabilityZone(formats strfmt.Registry) error {

	if err := validate.RequiredString("availabilityZone", "body", string(m.AvailabilityZone)); err != nil {
		return err
	}

	return nil
}

func (m *VolumeGroupSpec) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *VolumeGroupSpec) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *VolumeGroupSpec) validateProfiles(formats strfmt.Registry) error {

	if err := validate.Required("profiles", "body", m.Profiles); err != nil {
		return err
	}

	return nil
}

func (m *VolumeGroupSpec) validateProjectID(formats strfmt.Registry) error {

	if err := validate.RequiredString("projectId", "body", string(m.ProjectID)); err != nil {
		return err
	}

	return nil
}

func (m *VolumeGroupSpec) validateStatus(formats strfmt.Registry) error {

	if err := validate.RequiredString("status", "body", string(m.Status)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VolumeGroupSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VolumeGroupSpec) UnmarshalBinary(b []byte) error {
	var res VolumeGroupSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
