name: SODA API CI Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    env:
      GO111MODULE: on
      TARGET: amd64
        
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Checkout project  
      uses: actions/checkout@v3
      
    - name: Install Pre-requisites
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc librados-dev librbd-dev lvm2 tgt open-iscsi
        docker pull p1c2u/openapi-spec-validator
      
    - name: Build the binaries
      run: |
        make osdsapiserver
        make osdsctl

    - name: Run CI scripts for Testing
      run: ./install/CI/coverage && ./install/CI/test
    
    - name: After success run Codecov Coverage tool.
      uses: codecov/codecov-action@v2
    
    - name: Clean up the build
      run: |
        make clean
